### ISSUE TITLE
Invalid event handler property `onclick`. Did you mean `onClick`?

### ISSUE THREAD

**Issue by shutup7742** [aknuds1/html-to-react#101]
Hello. I was trying to run the code inside of the readme as a quick test. The code ran and I did get it to render beautifully. I am exited to use your software. I then decided that I wanted to run the code using a button instead of the header tag and the paragraph and that ran as I would expect. I did want to try adding a click event to this button 

`'<div><button onclick="console.log(\'hello\')">Hello World</button></div>';`

I ran the code and got the following error:

> Warning: Invalid event handler property `onclick`. Did you mean `onClick`?

I then changed it so that the on click was capitalized

` '<div><button onClick="console.log(\'hello\')">Hello World</button></div>';`

I got the same error. Is this an issue with your script? do you have any suggestions on how to fix the issue that I am having?

Also I don't understand why assert.equal is throwing and error with react

> 'assert' is not defined  no-undef

The code I used

```
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';

var ReactDOMServer = require('react-dom/server');
var HtmlToReactParser = require('html-to-react').Parser;

var htmlInput = '<div><button onClick="console.log(\'hello\')">Hello World</button></div>';
var htmlToReactParser = new HtmlToReactParser();
var reactElement = htmlToReactParser.parse(htmlInput);
var reactHtml = ReactDOMServer.renderToStaticMarkup(reactElement);
console.log(htmlInput);
console.log(htmlToReactParser);
console.log(reactElement);
console.log(reactHtml)

ReactDOM.render(reactElement, document.getElementById('root'));
/*
replaced with html-to-react component.
ReactDOM.render(<App />, document.getElementById('root'));
*/

//assert.equal(reactHtml, htmlInput); // true gets error 'assert' is not defined  no-undef

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();
```

**Comment by aknuds1** [comment]
About `assert.equal`, I guess you will need to import the [assert](https://www.npmjs.com/package/assert) module.

**Comment by aknuds1** [comment]
I just released version 1.4.2, which supports `onclick` attributes of HTML elements, can you please try it and see if it works for you?

**Comment by uragecz** [comment]
@aknuds1  Well it doesn't work.. now it says that `onClick` listener to be a function, instead got a value of `string` type...  source looks like this - <a onclick="alert('something');" ...

**Comment by aknuds1** [comment]
Can you make a PR with a failing test case @uragecz ?

**Comment by Bartaf83** [comment]
i got Warning: Invalid event handler property `onclick`. Did you mean `onClick`? too
"html-react-parser": "^0.13.0",

**Comment by maltoze** [comment]
@aknuds1 https://codesandbox.io/s/compassionate-benz-5rhk9?file=/src/App.js

**Comment by aknuds1** [comment]
@maltoze please make a PR with a failing test case.

**Comment by maltoze** [comment]
@aknuds1 https://github.com/aknuds1/html-to-react/pull/124

**Comment by uds214125** [comment]
I am facing the same issue. Any update.

**Comment by aknuds1** [comment]
@uds214125 I merged what I think is a fix.

If anyone is still facing this bug in version 1.4.7+, please let me know.

**Comment by thompsong** [comment]
I still see this error for custom attributes for drag and drop etc.

**Comment by ikthedar** [comment]
make sure you have written correctly. {onClick}
