### ISSUE TITLE
Return only a designated sub-node of the React-component tree?

### ISSUE THREAD

**Issue by MikeTaylor** [aknuds1/html-to-react#107]
For reasons I won't go into, the HTML template that I am going to generate will be of a complete HTML document, `<html><head>...</head><body><div>...</div></body></head>`. Is there an easy way to have `htmlToReactParser.parse` return the React component tree of only the `<div>`? Or, otherwise, to pluck that node out of the returned value myself, and use only it?

**Comment by dane-du-plessis** [comment]
I'm trying to do some thing similar with custom tags in the md file.

**Comment by MikeTaylor** [comment]
(For whatever it's worth, I ended up doing something different; so I no longer need this issue to be open for myself; but @dane-du-plessis's concerns may still be relevant.)
