### ISSUE TITLE
I've wrapped html in a div, and it keeps saying there are more than 1 root element.

### ISSUE THREAD

**Issue by pcompassion** [aknuds1/html-to-react#11]
> parser.js:49 Uncaught (in promise) Error: html-to-react currently only supports HTML with one single root element. The HTML provided contains 3 root elements. You can fix that by simply wrapping your HTML in a div element

Below is output in the chrome console when I'm on `Html2ReactParser` function.

I left spaces unchanged because maybe it's affecting the parsing?

html
```
"

<div>
  

<div class="form-group purchaser-fullname required">
    
    <label class="control-label" for="id_purchaser-fullname"></label>
    
    
        <input class="form-control" id="id_purchaser-fullname" name="purchaser-fullname" placeholder="이름" type="text" />
    
    
    
    

    

    
</div>



<div class="form-group purchaser-phone">
    
    <label class="control-label" for="id_purchaser-phone"></label>
    
    
        <input class="form-control" id="id_purchaser-phone" name="purchaser-phone" placeholder="전화번호" type="tel" />
    
    
    
    

    

    
</div>



<div class="form-group purchaser-email required">
    
    <label class="control-label" for="id_purchaser-email"></label>
    
    
        <input class="form-control" id="id_purchaser-email" maxlength="128" name="purchaser-email" placeholder="Email 주소" type="email" />
    
    
    
    

    

    
</div>



<input id="id_purchaser-email_real" name="purchaser-email_real" placeholder="None" type="hidden" />


</div>
"


```

handler.dom
```

[Object, Object, Object]

array[3]
0
:
Object
data
:
"↵↵"
next
:
Object
parent
:
null
prev
:
null
type
:
"text"
__proto__
:
Object
1
:
Object
attribs
:
Object
children
:
Array[9]
name
:
"div"
next
:
Object
parent
:
null
prev
:
Object
type
:
"tag"
__proto__
:
Object
2
:
Object
data
:
"↵"
next
:
null
parent
:
null
prev
:
Object
type
:
"text"
__proto__
:
Object
length
:
3
__proto__
:
Array[0]
```

**Comment by pcompassion** [comment]
Yeah, after I remove whitespace using `https://github.com/anseki/htmlclean` it doesn't give me the error anymore.

Now I want to render the result of the parse. Can't I use it like the following?
```

    var reactComponent = htmlToReactParser.parse(htmlclean(forms.purchaser))

    return (
      <reactComponent
        />
    )
```

**Comment by aknuds1** [comment]
I'm not much of a JSX expert, but what you receive from parsing HTML with html-to-react is not a React component, but rather an element. So I wouldn't think your JSX would be valid, you should treat `reactComponent` as an already rendered element instead.

**Comment by aknuds1** [comment]
An example of how you might use an html-to-react rendered element from JSX:

    const reactElement = htmlToReactParser.parse(html)
    (
      <h1>As rendered by html-to-react</h1>
      {reactElement}
    )
