### ISSUE TITLE
<code> <- </code> is parsed incorrectly

### ISSUE THREAD

**Issue by gilisho** [aknuds1/html-to-react#115]
I'm using `react-markdown` library which is using `html-to-react` under the hood.
Apparently the following html is not parsed correctly by `htmlparser2`:
```
<code>
 blabla <- blabla
</code>
```

https://github.com/aknuds1/html-to-react/issues/91#issuecomment-504085161
Is there an option to use `parse5` instead of `htmlparse2`? It feels more logical to allow to parse this html into react correctly.

How to reproduce: 
1. Go here: https://rexxars.github.io/react-markdown/
2. Paste the html from above.
--> Error is thrown in console.

**Comment by aknuds1** [comment]
Could you provide a PR with a test case for this issue?

**Comment by gilisho** [comment]
Sure. Here - https://github.com/aknuds1/html-to-react/pull/116

**Comment by aknuds1** [comment]
Ah, from your test case I see the issue. I'm actually unsure if this is valid HTML or not and am just assuming that htmlparser2 doesn't handle it. Do you want to make a PR to add parse5 as an optional back-end?

**Comment by aknuds1** [comment]
Can you validate your claim that this is valid HTML btw? Shouldn't it be encoded as follows instead, to be valid?

```html
<code>
 blabla &lt;- blabla
</code>
```

**Comment by aknuds1** [comment]
In fact, when I test this with https://html5.validator.nu, it points out exactly what I say above:

> Error: Bad character - after <. Probable cause: Unescaped <. Try escaping it as &lt;.

**Comment by aknuds1** [comment]
Closing this as it's invalid HTML. If you want to make an optional parse5 back-end, please open a PR with the implementation.

**Comment by gilisho** [comment]
I understand. Well, maybe it would be worth to add escaping to the html before sending it to the `htmlparse2`?
Github handles this as well. Type this in a comment in Github:
```
<code>
 blabla <- blabla
</code>
```
and this is the output:
<code>
 blabla <- blabla
</code>

I can try to add a PR for the escaping if you agree. I think this will help some consumes like me.

**Comment by aknuds1** [comment]
Escaping HTML is out of the scope of this library, it's better to do it before passing HTML to html-to-react.
