### ISSUE TITLE
Unknown prop for img

### ISSUE THREAD

**Issue by andrewl913** [aknuds1/html-to-react#13]
Have issues with img elements with our adaptive-src attribute 

Warning: Unknown prop `adaptive-src` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div
    in div
    in div
    in div
    in div
    in div
    in div (created by App)
    in App

**Comment by aknuds1** [comment]
I've never heard of this attribute on`img`, it's not among [the standard attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Attributes). Where does it come from?

**Comment by andrewl913** [comment]
Yeah, it's a custom attribute we use for images to dynamically scale based on their viewport. The alternative is to just use  "dangerously set innerHTML" but we are trying to avoid using this. The script cant change because it we have legacy CMS generated markup.

**Comment by aknuds1** [comment]
As you can see from https://facebook.github.io/react/warnings/unknown-prop.html however, React itself won't accept your nonstandard property. It's not to do with html-to-react.
