### ISSUE TITLE
Function statements require a function name in v1.4.6

### ISSUE THREAD

**Issue by ArtemNizelnyk** [aknuds1/html-to-react#133]
v 1.4.6\1.47 contains a bug

**Problematic code:**
```
      } else if (startsWith('on', key)) {
        value = Function(value);
}
```
**StackTrace:**
> 3:54:08 PM: SyntaxError: Function statements require a function name
> 3:54:08 PM:     at Function (<anonymous>)
> 3:54:08 PM:     at XWrap.f (/opt/build/repo/node_modules/html-to-react/lib/utils.js:79:17)
> 3:54:08 PM:     at XWrap.@@transducer/step (/opt/build/repo/node_modules/ramda/src/internal/_xwrap.js:17:17)
> 3:54:08 PM:     at _arrayReduce (/opt/build/repo/node_modules/ramda/src/internal/_reduce.js:18:34)
> 3:54:08 PM:     at _reduce (/opt/build/repo/node_modules/ramda/src/internal/_reduce.js:60:12)
> 3:54:08 PM:     at f3 (/opt/build/repo/node_modules/ramda/src/internal/_curry3.js:55:14)
> 3:54:08 PM:     at Object.createElement (/opt/build/repo/node_modules/html-to-react/lib/utils.js:68:20)
> 3:54:08 PM:     at Object.processDefaultNode (/opt/build/repo/node_modules/html-to-react/lib/process-node-definitions.js:25:20)
> 3:54:08 PM:     at Object.module.exports.nenm.exports.processDefaultNode (/opt/build/repo/.next/server/pages/404.js:4109:35)
> 3:54:08 PM:     at Object.processNode (/opt/build/repo/.next/server/pages/404.js:644:44)
> 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unnamed_function_statement

Please let me know if you need more details.

**Comment by aknuds1** [comment]
Do you have some example HTML that triggers the bug? I can't see anything wrong with the `Function` invocation on line 79 of lib/utils.js.

**Comment by ArtemNizelnyk** [comment]
[testOnClickFor1.4.6.txt](https://github.com/aknuds1/html-to-react/files/7187215/testOnClickFor1.4.6.txt)

Here is a sample.
The problem is with the anonymous functions:
`function() { return 1; }`

If `value` is defined like this, every on*** attribute parsing will fail.

Interesting is that `() => return 1;` works.

**Comment by ArtemNizelnyk** [comment]
I guess, I need to fix it in my lib and somehow stop CJS transform from `() => eval(onclick)` to `function () { return eval(onclick); }`

**Comment by aknuds1** [comment]
Your test code is broken, on account of replacing the `onclick` HTML node string attribute with an attribute `onClick` of type `Function`. The `onclick` HTML node attribute (`onClick` is how React cases it, not HTML) should be a string, not a function, that's why you get a bug.
