### ISSUE TITLE
Add TypeScript declarations

### ISSUE THREAD

**Issue by danikaze** [aknuds1/html-to-react#134]
As the title says :)
Include the .d.ts file within the package itself or in the [@types](https://github.com/DefinitelyTyped/DefinitelyTyped) repository.

**Comment by aknuds1** [comment]
A PR would be welcome. I'm not a TypeScript developer myself.

**Comment by Misfits09** [comment]
I've began to do something but finally found a more suitable library for Typescript...
I leave it here if someone want to test and finalize it

`index.d.ts`
```ts
type processingInstruction = {
  shouldProcessNode: (node: JSX.Element) => boolean;
  processNode: (node: JSX.Element, childrenNodes: JSX.Element[]) => JSX.Element;
};

export declare class Parser {
  constructor();

  parse(html: string): JSX.Element;
  parseWithInstructions(
    html: string,
    isValidNode: (node: JSX.Element) => boolean,
    processingInstructions: processingInstruction[],
  ): JSX.Element;
}

```

**Comment by fbec76** [comment]
@Misfits09 could you please share a link to that library.?
It would be really helpful.
Otherwise i could take a look at your index.d.ts and maybe finalize it.

**Comment by Misfits09** [comment]
> @Misfits09 could you please share a link to that library.?
> 
> It would be really helpful.
> 
> Otherwise i could take a look at your index.d.ts and maybe finalize it.
> 
> 
> 
> Edit: Here is a typescript libary that does the job pretty well [html-react-parser](https://www.npmjs.com/package/html-react-parser)
> 
> 

That's the one I used too !

**Comment by xnevz** [comment]
I goin' to fork this library to try add typescript support to it.

**Comment by aknuds1** [comment]
@xnevz feel free to make a PR back to this repo, once you've got it working :)

**Comment by emlynmac** [comment]
https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html has details on how to do this in an automated way.
Let me fork, test and PR

**Comment by xnevz** [comment]
@aknuds1 Close this issue, since it has been resolved ! Thanks.
