### ISSUE TITLE
Should href attribute be encoded

### ISSUE THREAD

**Issue by gerhardsletten** [aknuds1/html-to-react#14]
We are using this library to parse and display content from wordpress-api and there & in urls are encoded to &amp; 

When we parse and insert content with html-to-react these attributes are encoded another time, resulting in links that are not working:

`<a href="http://domain.com/search?query=xy&amp;amp;publications=5">Some link</a>`

Is this a bug in html-to-react? It it is, I can submit an PR

**Comment by aknuds1** [comment]
Good question Gerhard, but it appears to be the case that ampersands (`&`) *should* be HTML encoded inside of attribute values. It's actually not html-to-react that does this, but React itself. You can check [this SO answer](http://stackoverflow.com/a/3705601/265261) for reference.

**Comment by aknuds1** [comment]
Actually, having had another look at the issue I guess it's the other way around, you mean that `&` in URLs are encoded to `&amp;`? It might be the case that html-to-react should decode these to `&` before calling `React.createElement`, since the latter encodes the HTML.

**Comment by aknuds1** [comment]
So, basically, since I can confirm that HTML character entities in attributes get re-encoded, please submit a PR :)

**Comment by gerhardsletten** [comment]
@aknuds1 Great, then I will have a look at it
