### ISSUE TITLE
Release 1.5.0 fails to compile "Module parse failed: Unexpected token"

### ISSUE THREAD

**Issue by kjain1995** [aknuds1/html-to-react#141]
I recently updated my application to the v1.5.0, and since then I get the following error:

> ERROR in ./node_modules/domhandler/lib/esm/node.js
Module parse failed: Unexpected token (284:47)
You may need an appropriate loader to handle this file type.
|     else if (isTag(node)) {
|         const children = recursive ? cloneChildren(node.children) : [];
|         const clone = new Element(node.name, { ...node.attribs }, children);
|         children.forEach((child) => (child.parent = clone));
|         if (node.namespace != null) {
 @ ./node_modules/domhandler/lib/esm/index.js 2:0-92 3:0-26
 @ ./node_modules/html-to-react/lib/parser.js
 @ ./node_modules/html-to-react/index.js
...

> 

 When I downgrade back to `1.4.7`, it works fine. Seems to be a problem only with the latest release.

Node version: 12.13.1
npm: 6.12.0
webpack: 3.12.0

**Comment by aknuds1** [comment]
Node 14 is the earliest supported version, but I just tried `npm test` on the repo with Node 12.22.12 and it works. You'll have to provide instructions on how to reproduce.

Additionally, your parse error occurs for a dependency of html-to-react, i.e. domhandler. Therefore it might be better for you to eventually raise an issue with that project.

Closing this issue until more information surfaces pointing towards a problem in html-to-react.
