### ISSUE TITLE
Using with webpack: ERROR in ./~/ent/reversed.json

### ISSUE THREAD

**Issue by optimatex** [aknuds1/html-to-react#18]
Hi. I encountered this error. I installed https://www.npmjs.com/package/json-loader but this didn't help me.
Full list of errors in bundle
1) ERROR in ./~/ent/entities.json  Module parse failed: D:\reflex\front-end\node_modules\ent\entities.json Unexpected token (2:13)
You may need an appropriate loader to handle this file type.
2) ERROR in ./~/ent/reversed.json
Module parse failed: D:\reflex\front-end\node_modules\ent\reversed.json Unexpected token (2:7)
You may need an appropriate loader to handle this file type.
3) ERROR in ./~/entities/maps/legacy.json
Module parse failed: D:\reflex\front-end\node_modules\entities\maps\legacy.json Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
4) ERROR in ./~/entities/maps/xml.json
Module parse failed: D:\reflex\front-end\node_modules\entities\maps\xml.json Unexpected token (1:6) You may need an appropriate loader to handle this file type.
5) ERROR in ./~/entities/maps/entities.json
Module parse failed: D:\reflex\front-end\node_modules\entities\maps\entities.json Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
6) ERROR in ./~/entities/maps/decode.json
Module parse failed: D:\reflex\front-end\node_modules\entities\maps\decode.json Unexpected token (1:4)

**Comment by aknuds1** [comment]
I haven't used webpack in a while, so I can't help you too much, but it looks like webpack is trying to load a JSON file which it shouldn't. I would ask for help in the webpack channel on Gitter. Besides, the error is due to the ent package, and not html-to-react itself.

**Comment by optimatex** [comment]
Thank u for help. And also thanks for revealing Gitter. Never heard about it before

**Comment by optimatex** [comment]
I have found solution: 
`{
test: /\.json$/,
loader: 'json-loader',
},`
u need to include this into webpack config files into loaders section

**Comment by aknuds1** [comment]
@optimatex If I recall correctly, you should tell webpack to ignore that json file somehow, not load it.

**Comment by optimatex** [comment]
@aknuds1 thanks i'll try to find what load json file. At this point i have no idea how to do this. But thanks
