### ISSUE TITLE
Unable to resolve module 'events' from '~/xxxApp/node_modules/htmlparser2/lib/Parser.js

### ISSUE THREAD

**Issue by dktan** [aknuds1/html-to-react#19]
Unable to resolve module 'events' from '~/xxxApp/node_modules/htmlparser2/lib/Parser.js

**Comment by aknuds1** [comment]
How does this happen? In any case, the error is in another package than html-to-react, namely [htmlparser2](https://github.com/fb55/htmlparser2), so I doubt that it has to do with html-to-react.

**Comment by dktan** [comment]
I used it on react-native project.....

**Comment by aknuds1** [comment]
I have never tried it with react-native, no idea if it will work. Anyway, this isn't an issue with html-to-react, but possibly htmlparser2, so closing.
