### ISSUE TITLE
Cannot read property 'length' of undefined when inline style contains font-family property

### ISSUE THREAD

**Issue by Gycianka** [aknuds1/html-to-react#20]
[createStyleJsonFromString](https://github.com/aknuds1/html-to-react/blob/master/lib/utils.js#L19) gives:

> Cannot read property 'length' of undefined

When your html string contains font-family css property e.g. `Sans&quot margin: 0px 0px 15px; padding: 0px; text-align: justify; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px;
`

**Comment by aknuds1** [comment]
Can you provide a PR with a test reproducing the bug?

**Comment by Gycianka** [comment]
Done: #21
The problem is special html characters. I'm not sure if this is problem that you should fix or not.
