### ISSUE TITLE
reduce lib size 

### ISSUE THREAD

**Issue by giuseppeg** [aknuds1/html-to-react#22]
It seems that the library is 1.38 MB, is there any chance to shrink it?
I think that the lib is very interesting but I wouldn't be able to use it if it is that big in size.

**Comment by aknuds1** [comment]
A minified browserify bundle of the latest version weighs in at 268k for me, produced like this: `browserify -p [ minifyify --no-map ] -o dist/bundle.js index.js`.

Maybe you could produce a PR for making it even smaller?

**Comment by aknuds1** [comment]
I was able to reduce the minified size to 152k actually, after being more specific with what we import from htmlparser2 and by eliminating our dependency on the ent library.

**Comment by giuseppeg** [comment]
awesome thank you! I think that you forgot to build an publish `dist`.
I will try with rollup when I have a spare 30 mins :)

**Comment by aknuds1** [comment]
I'm actually not sure what's the purpose of the dist/ bundle, to be quite honest. It was there when I took over the project, and I'm thinking people would have better ways of including the lib in their project by now. Do you see any need for it?

**Comment by giuseppeg** [comment]
No I don't see any point in keeping the `dist` folder in the repo.
However I would add the `files` field in `package.json` and a build script to bundle the lib before publishing (`prepublish`) and expose it as an UMD module. 
Keeping tests and the source code in the npm package is not necessary.
