### ISSUE TITLE
How to transform ↵ symbol?

### ISSUE THREAD

**Issue by optimatex** [aknuds1/html-to-react#23]
Hi. Thanks for cool module. But I encountered issue that I need to transform ↵ symbol into <br> tagname. Is it a feature that I might accomplish with html-to-react?

**Comment by aknuds1** [comment]
What kind of tag should ↵ translate into? It doesn't sound like it's in the scope of html-to-react to be quite honest.

**Comment by optimatex** [comment]
I'd like to translate it to <br/> tag. If it is not possible I'll try other ways to solve this. I just thought that since your module parse html string it can search for symbols too.

**Comment by aknuds1** [comment]
OK, I see what you want. It's not in html-to-react's scope though; as you can tell from the library's name, its purpose is to translate HTML markup to React elements, which hasn't to do with translating from one HTML representation to another.

**Comment by optimatex** [comment]
Ok, thanks anyway. Sorry
