### ISSUE TITLE
Breaks on inline base64 images in styles

### ISSUE THREAD

**Issue by aleemb** [aknuds1/html-to-react#32]
Issue #28 fixes `:` bug due to the `background-image` property containing a `:` as per

```
background-image:url(http://foo.com)
```

In a similar class of bugs is an inline style containing a `;`

```
background-image:url(data:image/png;base64,iVBORw0KGgoAAA)
```

Since styles are split on `;` this breaks.

**Comment by aknuds1** [comment]
Would you mind submitting a PR please with a test corresponding to the bug?

**Comment by aleemb** [comment]
@aknuds1 submitted PR. Unit tests passing and tested within my app, LGTM.
