### ISSUE TITLE
Whitespace warnings

### ISSUE THREAD

**Issue by rstacruz** [aknuds1/html-to-react#37]
Code like `<div style="margin: 0; padding: 0;">` yields this warning:

![image](https://user-images.githubusercontent.com/74385/27262891-a0a41f9e-5492-11e7-8eb9-742e2dbc2c9f.png)

Omitting the spaces (`margin:0;padding:0;`) works as a workaround.

**Comment by aknuds1** [comment]
This is solved the quickest if you provide a PR with a test for your scenario, and preferably a solution to make the test pass.

**Comment by nickpalmer** [comment]
This was fixed in 1bf42375.

**Comment by aknuds1** [comment]
I guess we can close it then :)
