### ISSUE TITLE
Question: Why do empty attributes get the key as value

### ISSUE THREAD

**Issue by koenvg** [aknuds1/html-to-react#40]
Is there a reason why empty attributes get the key as value?

This is the part of the code responsible for this behaviour. It looks intentionally written but it gives unwanted behaviour in my project.

`result[key] = value || key;`

**Comment by aknuds1** [comment]
The easiest way to figure this out is to remove the logic you're wondering about and run the tests (`npm test`). It will make one test fail: _should fill in the key name with boolean attribute_. The test shows why this logic is necessary, i.e. to support value-less HTML attributes.
