### ISSUE TITLE
Not parse attributes of custom elements

### ISSUE THREAD

**Issue by lsroman** [aknuds1/html-to-react#43]
Official react docs  "One common confusion is that Web Components use "class" instead of "className"."
Html-to-react:
Input: `<custom-node class="test"></custom-node>`
Output: `<custom-node classname="test"></custom-node>`
React-tool(official parser JSX):
Input: `<custom-node class="test"></custom-node>`
Output: `<custom-node class="test"></custom-node>`

**Comment by aknuds1** [comment]
I don't really understand what you mean by this issue, but feel free to make a PR.

**Comment by aknuds1** [comment]
I'll close, since no clarification has been made in the meantime.

**Comment by aknuds1** [comment]
Fixed by #151.
