### ISSUE TITLE
How do I change css of processed node?

### ISSUE THREAD

**Issue by ahmadsholehin** [aknuds1/html-to-react#45]
I'm trying to do something like below in a processing instruction. The code below is definitely not-working as the `node` argument is by no means a DOM node.

Anyone has any ideas how this can be implemented?

```
// code not working
{
    shouldProcessNode: node => node.attribs && node.attribs['data-bg-image'],
    processNode: ( node, children, i ) => {
      const $el = $( node ); // node cannot be jquer-ied this way
      $el.css( { 'background-image': 'url(' + node.attribs['data-bg-image'] + ')' } );
      return children;
    }
  }
```

**Comment by nickpalmer** [comment]
Don't do it via jquery. Node is not a 'node' it is just an object representing the html.
I recommend passing the node off to the default rendering mechanism after modification.

```
const defaults = new ProcessNodeDefinitions(React);
// ...
{
    shouldProcessNode: node => node.attribs && node.attribs['data-bg-image'],
    processNode: ( node, ...args) => {
      node.attribs.style = 'background-image: url(' + node.attribs['data-bg-image'] + ')';
      return defaults.processDefaultNode(node, ...args);
    }
 }
```

**Comment by ahmadsholehin** [comment]
Understood. That's important to take note of. Didn't know that you can mutate a node that way and pass it off in `defaults.processDefaultNode(node, ...args)`. That should come in handy.

I was thinking if it would be nice if a `ref` attribute could be passed in as well. Something like below:
```
{
    shouldProcessNode: node => node.attribs && node.attribs['data-bg-image'],
    processNode: ( node, ...args) => {
      node.attribs.ref = someRefFunction;
      return defaults.processDefaultNode(node, ...args);
    }
 }

function someRefFunction( el ) {
    if ( !el  ) return;
    this.thatNode = el;
    // .. do something else with this node since ref will be called when it has mounted
}
```

I'm not entirely sure if this would work though. But it certainly is useful (think binding some non-react jQuery plugins).

**Comment by aknuds1** [comment]
Mind if I close?

**Comment by nickpalmer** [comment]
You can certainly pass a ref function like that if you want. :+1: for closing this one as I think the question is answered, unless you want to update documentation to explain this use case to other users.
