### ISSUE TITLE
Extend resulting component

### ISSUE THREAD

**Issue by vonloxx** [aknuds1/html-to-react#62]
Hi,
How I would extend the resulting component from processNode (high order components)?
Probably there should be a postProcessNode callback at the processing instructions?

**Comment by aknuds1** [comment]
Sorry if I'm missing something, but can't you accomplish this by implementing `processNode` and extending the result from calling `processDefaultNode`?

**Comment by vonloxx** [comment]
@aknuds1 ok, nevermind. Kind of mixing components and elements. React newbie here 😉
