### ISSUE TITLE
import fails

### ISSUE THREAD

**Issue by mprevot** [aknuds1/html-to-react#63]
In a react component, instead of `var HtmlToReactParser = require('html-to-react').Parser;` I wanted to use `import HtmlToReactParser from 'html-to-react';` but it fails with "xx is not a constructor" when I call `var parser = new HtmlToReactParser();`

Do you recommend a way to do this ?

**Comment by aknuds1** [comment]
@mprevot I'm afraid I haven't tried the new `import` syntax yet, sorry :/ Does the following work though? 

    import {Parser,} from 'html-to-react'
    var parser = new Parser()

**Comment by mprevot** [comment]
It's indeed the right syntax !
You might want to add this to readme.md

Regards

2018-04-12 15:35 GMT+02:00 Arve Knudsen <notifications@github.com>:
