### ISSUE TITLE
Parser.parse() is not a function

### ISSUE THREAD

**Issue by GabrielInTheWorld** [aknuds1/html-to-react#64]
When I tried to parse a html-string with the simple function "parse(html)" of the imported parser, an error occurred that "parse" is not a function...

**Comment by aknuds1** [comment]
Can you provide a code example?

**Comment by GabrielInTheWorld** [comment]
`let elem = Parser.parse(rawHTML)`

**Comment by aknuds1** [comment]
Can you please provide a full example including imports?

**Comment by aknuds1** [comment]
I'm going to close this, as I suspect it's a matter of using the library in the wrong way. Please re-open if you have more info :)
