### ISSUE TITLE
actual DOM node to React element

### ISSUE THREAD

**Issue by subhranshudas** [aknuds1/html-to-react#71]
Hi,

I have a scenario where i am creating a DIV node by using document.createElement('div') which i am then passing to an external library which inserts some mark up into that DIV. and after it inserts that markup, i want to use it in my render method to render the entire VIEW.

Is there an API in html-to-react to do that?

**Comment by aknuds1** [comment]
I think you could in part solve this by using processing instructions, but then you would need to convert your DOM element to a React component in order to inject it.  Unfortunately, html-to-react doesn't have any API for converting DOM elements.
