### ISSUE TITLE
Uncaught TypeError: DomHandler is not a constructor

### ISSUE THREAD

**Issue by pablohpsilva** [aknuds1/html-to-react#98]
Hello, good morning.

The `html-to-react` version I'm using is the latest.

I'm trying to parse the following string into JSX:
```
"By using the site, you acknowledge you have read our <a href=/privacy-policy>Privacy Policy</a>,
    and agree to our <a href=/terms-and-conditions>Terms and Conditions</a>."
```

For some reason, I get the following error stack:
```
parser.js:16 Uncaught TypeError: DomHandler is not a constructor
    at parseHtmlToTree (parser.js:16)
    at parseWithInstructions (parser.js:61)
    at Object.parse (parser.js:71)
```

I checked `domhandler` package and apparently there are no breaking changes. Could you guys help?

**Comment by wintercounter** [comment]
Same issue here with `1.4.0`. Reverting to `1.3.4` works fine.

**Comment by aknuds1** [comment]
Does the test suite of html-to-react fail for you? It works locally this looks like something that would break as part of the test suite.

**Comment by aknuds1** [comment]
I think you must have stale dependencies, since I upgraded the domhandler package and I'm using it according to current API and it does work locally for me.

**Comment by wintercounter** [comment]
I'm on holidays this week, I can try later. Maybe it our internal Nexus
repository's cache making us fool.

**Comment by julianaleon** [comment]
I'm seeing the same error:
<img width="849" alt="Screen Shot 2019-09-04 at 4 09 47 PM" src="https://user-images.githubusercontent.com/6567368/64291712-7501ac80-cf2e-11e9-9208-18ba913d5a21.png">

**Comment by aknuds1** [comment]
@julianaleon Have you verified your dependencies are not stale, as I mentioned as a distinct possibility earlier for this issue?

**Comment by tiyunchen** [comment]
any update?

**Comment by aknuds1** [comment]
@tiyunchen Please see my questions in earlier comments regarding stale dependencies.

Closing the issue for now, due to inactivity.
